api_url: https://enpaku-jdta.jp/api
github_pages_url: https://nakamura196.github.io/dataset_enpaku
identifier: dcterms:identifier

output_dir: ../docs
metadata:
  dcterms:identifier: ID
  dcterms:isPartOf: ウェブサイトURL
  dcterms:relation: アイテムURL
  dcterms:rights: 利用条件
  foaf:thumbnail: サムネイル
  rdfs:seeAlso: 機械可読ドキュメント
  sc:attributionLabel: 帰属
  sc:viewingDirection: viewingDirection
  uterms:manifestUri: IIIFマニフェストURI
  uterms:searchApiUri: IIIF Search API URI
sort: uterms:sort
base_url: https://dch.iii.u-tokyo.ac.jp/s/dch/record
list_path: ../docs/list.json
key_identity: JEUsVhdZrQiivrp2R6q5VGMC4yjkEG3f
key_credential: DNjpqriFn9GZ9rlBr4hCIKisEvV4Mo0X
